# Generated by Django 3.0.5 on 2021-05-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='product_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
